name: teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - sphinx
  - matplotlib
  - sympy
  - pip
  - rpy2
  - pip:
    - ghp-import
    - nibabel
    - scipy
    - texext
    - nb2plots
