name: teaching-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - sphinx
  - matplotlib
  - sympy
  - pip
  - pip:
   - ghp-import
   - nibabel
   - scipy
   - texext
   - nb2plots
